env: "local" #local, dev, prod
http_server:
  address: "localhost:8083"
  read_timeout: 15ms
  processing_timeout: 20ms
  write_timeout: 15ms
  idle_timeout: 30s

postgres:
  db_name: "realty"
  user: "realty-user"
  password: "realty-password"
  port: 54321
  host: "localhost"