env: "local" #local, dev, prod
storage_path: "./storage/storage.db" # для sqlite
http_server:
  address: "localhost:8082"
  read_timeout: 15ms
  processing_timeout: 20ms
  write_timeout: 15ms
  idle_timeout: 30s