version: '3'

volumes:
  realty_postgres_volume_local:

services:
  realty-pg-local:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "54321:5432"
    volumes:
      - realty_postgres_volume_local:/var/lib/postgresql/data
